"""init

Revision ID: dbb8d144fad1
Revises:
Create Date: 2024-09-01 21:32:56.785956+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbb8d144fad1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("info_channel_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("guild_id", sa.String(), nullable=True),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "author_id", "guild_id"),
    )
    op.create_index(op.f("ix_playlist_author_id"), "playlist", ["author_id"], unique=False)
    op.create_table(
        "guild_phrase",
        sa.Column("hash_key", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("guild_id", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild.id"],
        ),
        sa.PrimaryKeyConstraint("hash_key"),
        sa.UniqueConstraint("guild_id", "hash_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guild_phrase")
    op.drop_index(op.f("ix_playlist_author_id"), table_name="playlist")
    op.drop_table("playlist")
    op.drop_table("guild")
    # ### end Alembic commands ###
