"""replace attachment_url with attachment_data and filename

Revision ID: ee8b8eb9f7fe
Revises: dbb8d144fad1
Create Date: 2026-01-30 23:27:27.903319+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee8b8eb9f7fe"
down_revision: Union[str, None] = "dbb8d144fad1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guild_phrase", sa.Column("attachment_data", sa.LargeBinary(), nullable=True))
    op.add_column("guild_phrase", sa.Column("attachment_filename", sa.String(), nullable=True))
    op.add_column("guild_phrase", sa.Column("specific_users_id", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guild_phrase", "specific_users_id")
    op.drop_column("guild_phrase", "attachment_filename")
    op.drop_column("guild_phrase", "attachment_data")
    # ### end Alembic commands ###
