name: Deployment

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR has no-deployment label
      id: check_deployment
      uses: shioyang/check-pr-labels-on-push-action@v1.0.12
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["no-deployment"]'
      timeout-minutes: 5
    outputs:
      deploy: "${{ ! steps.check_deployment.outputs.result }}"

  pre_commit_ci:
    uses: MorpheusBot/Morpheus-bot/.github/workflows/lint.yml@master

  deployment_production:
    runs-on: ubuntu-latest
    environment: Production
    needs: [pre_commit_ci, check_deployment]
    if: github.ref == 'refs/heads/main' && needs.check_deployment.outputs.deploy == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          port: 22
          script: |
            echo "================== Pull Changes =================="
            cd Morpheus
            git pull

            echo "================== Build and Push Image =================="
            docker build . --tag morpheus-bot

            echo "================== Restart Services =================="
            docker compose down && docker compose up -d

            echo "================== Clean Up Images =================="
            echo "y" | docker image prune -a
